Algoritmo "Custo_carro"
// Professor   : Cintia Pinho
// Autor(a)    : Luiza Pereira
Var
// Seção de Declarações das variáveis 

distancia,combustivel:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite a distância percorrida: ")
leia(distancia)

escreval("Digite o combustivel gasto: ")
leia(combustivel)

escreval("O consumo médio do combustivel do seu veículo é: ", distancia/combustivel)

Fimalgoritmo