Algoritmo "Numero_inicial_final"
 // Descriçao   :Fazer um algoritmo que escreva na tela os números de um número inicial até um final.
// Autor(a)    : Luiza Pereira Silva


Var
cont, y, z: inteiro

Inicio
escreval("Digite o número inicial:")
leia(y)
escreval("Digite o número final:")
leia(z)
escreval("-----------------------")

para cont de y até z faca
     escreval(y)
     y <- y + 1
fimpara

escreval("-----------------------")

Fimalgoritmo