Algoritmo "ParImpar"
// Descri??o   : Informar se o valor é par ou ímpar
// Autor(a)    : Luiza Pereira Silva

Var
// Seção de Declarações das variáveis

num: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval("Digite um valor: ")
leia(num)

se (num mod 2)= 0 entao

   escreval("Par")
   
senao

    escreval("Impar")

fimse

Fimalgoritmo